### ISSUE TITLE
delivery error 400

### ISSUE THREAD

**Issue by AdditionalLibraries-Dev** [Schubilegend/SchubiRat#8] opened 2023-09-11 09:01 UTC
![image](https://github.com/Schubilegend/SchubiRat/assets/103485880/1793eca4-b665-4ecb-a282-c415dfb5e900)
 it returns bad request even though it sends a normal post request I did everything according to the guide and I get this error.

**Comment by schubilegend** [comment] 2023-09-11 10:19
@Majanito

**Comment by Majanito** [comment] 2023-09-11 11:05
Could you provide instructions how to reproduce this/circumstances under which this happens, because I cannot replicate your issue.

**Comment by AdditionalLibraries-Dev** [comment] 2023-09-11 14:44
I downloaded the code in the zip archive, unzipped it,changed config, run it, copied the ip, through online java string editor changed your url to ip from the console, ran it, I get this error, the same thing happens to my friend.

**Comment by Audjfi1qw1232** [comment] 2023-09-15 20:00
> I downloaded the code in the zip archive, unzipped it,changed config, run it, copied the ip, through online java string editor changed your url to ip from the console, ran it, I get this error, the same thing happens to my friend.

I'm encountering the same problem

**Comment by Audjfi1qw1232** [comment] 2023-09-16 09:08
> Could you provide instructions how to reproduce this/circumstances under which this happens, because I cannot replicate your issue.

Try to replicate the issue:

First setup the render service, and do all the things according to the instructions,

After which setup the mod which is modified with a different URL,

And then try and launch a modpack with the modified mod and every single time the Render log returns this error:

"POST /delivery HTTP/1.1" 400 -

**Comment by schubilegend** [comment] 2023-09-20 08:53
@Majanito

**Comment by schubilegend** [comment] 2023-09-20 15:36
Sorry guys. Unfortunately we are too lazy to replicate your issue and fix it. If you want us to do it then you have to pay.

**Comment by schubilegend** [comment] 2023-09-20 15:37
add me on dc

**Comment by Majanito** [comment] 2023-09-26 19:38
Should be fixed now

**Closed as completed by Majanito** 2023-09-26 19:38 UTC
